export interface AlertsData {
  id: string
  label: string
  sku: string
  dc: string
  store: string
  status: "In Progress" | "Pending" | "Resolved" | "Backlog" | "Canceled"
  title: string
  risk: string
  resolution: string
}

export const alertsData: AlertsData[] = [
  // Accounts Payable Alerts
  {
    id: "ap-1",
    label: "Accounts Payable",
    sku: "AP-Invoice-10045",
    dc: "Corporate",
    store: "Global",
    status: "In Progress",
    title: "Early payment discount opportunity expiring in 48 hours",
    risk: "$15,000 Discount Loss",
    resolution: "Process payment immediately to capture 2% discount",
  },
  {
    id: "ap-2",
    label: "Accounts Payable",
    sku: "AP-Vendor-8732",
    dc: "Corporate",
    store: "Global",
    status: "Backlog",
    title: "Duplicate invoice detected for vendor payment",
    risk: "$8,500 Potential Overpayment",
    resolution: "Verify invoice and contact vendor for clarification",
  },
  {
    id: "ap-3",
    label: "Accounts Payable",
    sku: "AP-Invoice-12876",
    dc: "Corporate",
    store: "Global",
    status: "Pending",
    title: "Vendor payment terms optimization opportunity",
    risk: "$12,300 Cash Flow Opportunity",
    resolution: "Renegotiate payment terms with vendor",
  },

  // Accounts Receivable Alerts
  {
    id: "ar-1",
    label: "Accounts Receivable",
    sku: "AR-Customer-5621",
    dc: "Corporate",
    store: "Northeast",
    status: "Pending",
    title: "Customer payment 30 days overdue",
    risk: "$42,000 Cash Flow Impact",
    resolution: "Escalate to collections team and contact customer",
  },
  {
    id: "ar-2",
    label: "Accounts Receivable",
    sku: "AR-Customer-7890",
    dc: "Corporate",
    store: "West",
    status: "In Progress",
    title: "Customer approaching credit limit",
    risk: "$75,000 Credit Risk",
    resolution: "Review credit history and consider limit increase",
  },
  {
    id: "ar-3",
    label: "Accounts Receivable",
    sku: "AR-Customer-4532",
    dc: "Corporate",
    store: "Southeast",
    status: "Backlog",
    title: "Recurring late payments from key customer",
    risk: "$28,500 Cash Flow Impact",
    resolution: "Schedule payment plan discussion with customer finance team",
  },

  // Cash Flow Alerts
  {
    id: "cf-1",
    label: "Cash Flow",
    sku: "CF-Forecast-Q3",
    dc: "Corporate",
    store: "Global",
    status: "In Progress",
    title: "Cash flow forecast shows 15% shortfall in Q3",
    risk: "$120,000 Liquidity Risk",
    resolution: "Accelerate collections and delay non-critical payments",
  },
  {
    id: "cf-2",
    label: "Cash Flow",
    sku: "CF-Banking-3421",
    dc: "Corporate",
    store: "Global",
    status: "Pending",
    title: "Excess cash in low-yield accounts",
    risk: "$8,000 Interest Income Loss",
    resolution: "Move funds to higher-yield short-term investments",
  },
  {
    id: "cf-3",
    label: "Cash Flow",
    sku: "CF-Seasonal-Q4",
    dc: "Corporate",
    store: "Global",
    status: "Backlog",
    title: "Seasonal cash flow gap identified for Q4",
    risk: "$95,000 Liquidity Risk",
    resolution: "Secure short-term credit line or factor receivables",
  },

  // Margin Alerts
  {
    id: "mg-1",
    label: "Margin",
    sku: "FRG-PX-4410",
    dc: "Boston",
    store: "Philadelphia",
    status: "Backlog",
    title: "Copper pipe fitting margin declined by 5% over last quarter",
    risk: "$32,000 Profit Impact",
    resolution: "Review pricing strategy and supplier negotiations with pipe manufacturers",
  },
  {
    id: "mg-2",
    label: "Margin",
    sku: "FRG-WH-3200",
    dc: "Chicago",
    store: "Detroit",
    status: "In Progress",
    title: "Water heater SKU margin below threshold of 25%",
    risk: "$18,500 Profit Impact",
    resolution: "Implement cost reduction or negotiate better terms with Rheem/A.O. Smith",
  },
  {
    id: "mg-3",
    label: "Margin",
    sku: "FRG-HV-5100",
    dc: "Dallas",
    store: "Houston",
    status: "Pending",
    title: "HVAC equipment line margin compression due to competition from Winsupply",
    risk: "$45,000 Profit Impact",
    resolution: "Conduct competitive analysis and revise HVAC pricing strategy",
  },

  // Working Capital Alerts
  {
    id: "wc-1",
    label: "Working Capital",
    sku: "WC-DIO-Q2",
    dc: "Corporate",
    store: "Global",
    status: "Pending",
    title: "Days Inventory Outstanding (DIO) increased to 65 days",
    risk: "$45,000 Working Capital Impact",
    resolution: "Optimize inventory levels and improve turnover",
  },
  {
    id: "wc-2",
    label: "Working Capital",
    sku: "WC-DSO-Q2",
    dc: "Corporate",
    store: "Global",
    status: "In Progress",
    title: "Days Sales Outstanding (DSO) increased to 48 days",
    risk: "$62,000 Working Capital Impact",
    resolution: "Implement early payment incentives and review credit terms",
  },
  {
    id: "wc-3",
    label: "Working Capital",
    sku: "WC-DPO-Q2",
    dc: "Corporate",
    store: "Global",
    status: "Resolved",
    title: "Days Payable Outstanding (DPO) optimized to 45 days",
    risk: "$0 (Optimized)",
    resolution: "Continue monitoring supplier payment terms",
  },
  {
    id: "wc-4",
    label: "Working Capital",
    sku: "WC-C2C-Q2",
    dc: "Corporate",
    store: "Global",
    status: "Backlog",
    title: "Cash-to-Cash cycle increased to 68 days",
    risk: "$85,000 Working Capital Impact",
    resolution: "Implement comprehensive working capital optimization plan",
  },

  // Tariff Alerts
  {
    id: "tf-1",
    label: "Tariffs",
    sku: "European-Brass-Valves",
    dc: "New York",
    store: "Global",
    status: "In Progress",
    title: "New tariff increase of 10% on imported brass valves and fittings",
    risk: "$38,000 Cost Impact",
    resolution: "Evaluate domestic sourcing from Nibco or apply for tariff exemption",
  },
  {
    id: "tf-2",
    label: "Tariffs",
    sku: "Chinese-PVC-Fittings",
    dc: "Los Angeles",
    store: "Global",
    status: "Pending",
    title: "Potential new tariffs announced on PVC fittings for Q4",
    risk: "$52,000 Potential Cost Impact",
    resolution: "Accelerate imports and build strategic inventory at distribution centers",
  },
  {
    id: "tf-3",
    label: "Tariffs",
    sku: "Korean-HVAC-Compressors",
    dc: "Boston",
    store: "Global",
    status: "Backlog",
    title: "Tariff classification audit recommended for HVAC compressor imports",
    risk: "$24,000 Potential Savings",
    resolution: "Conduct comprehensive HTS code review with customs broker for HVAC components",
  },

  // EBITDA Alerts
  {
    id: "eb-1",
    label: "EBITDA",
    sku: "EB-Q2-Forecast",
    dc: "Corporate",
    store: "Global",
    status: "Backlog",
    title: "EBITDA margin trending 3% below target",
    risk: "$175,000 Profit Impact",
    resolution: "Implement cost reduction initiatives across departments",
  },
  {
    id: "eb-2",
    label: "EBITDA",
    sku: "EB-Northeast-Region",
    dc: "Boston",
    store: "Northeast",
    status: "In Progress",
    title: "Regional EBITDA 8% below forecast",
    risk: "$95,000 Profit Impact",
    resolution: "Review regional pricing strategy and operational efficiency",
  },
  {
    id: "eb-3",
    label: "EBITDA",
    sku: "EB-OpEx-Q3",
    dc: "Corporate",
    store: "Global",
    status: "Pending",
    title: "Operating expenses exceeding budget by 12%",
    risk: "$135,000 Profit Impact",
    resolution: "Implement immediate expense controls and review discretionary spending",
  },
]
